name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Chạy action này khi có code push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Lên cấu hình & Deploy tới VPS qua SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }} # Sét IP server 36.50.135.61 trong Github Secrets
          username: ${{ secrets.SERVER_USERNAME }} # Tên user SSH (ví dụ: root)
          key: ${{ secrets.SERVER_SSH_KEY }} # Private SSH key
          port: ${{ secrets.SERVER_PORT }} # Thường là 22
          script: |
            # Di chuyển tới thư mục cài đặt dự án (bạn phải tạo trên server trước)
            cd /var/www/webbannuochoa || exit 1
            
            # Kéo (pull) bản code mới nhất
            git pull origin main
            
            # Tạo file .env an toàn từ Github Secrets
            echo "DB_HOST=db" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            
            # Tắt container cũ, build lại và khởi động mới bằng docker-compose
            docker-compose down
            docker-compose build
            docker-compose up -d
